export const BASE_URL = '/api/v1/movies/';
export const DELETE = 'delete'
export const HEADERS = 'headers'
export const NO_USER = { id: 0 }
export const USER_TOKEN_URL = '/api/v1/user_token/'
export const CURRENT_USER_URL = 'api/v1/users/current'
export const JWT = 'jwt'
export const BEARER = 'Bearer '
export const AUTHORIZATION = 'Authorization'